repos:
  - repo: local
    hooks:
      - id: biome-check
        name: Biome Check
        entry: bun run check:all
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: biome-format
        name: Biome Format
        entry: bun run format:all
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: typescript-check
        name: TypeScript Check
        entry: bunx tsc --noEmit
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: test-check
        name: Test Check
        entry: bun run test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
